// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhsSbSthzdE1K5Xxt5eGEALELaEq0iEFw',
    appId: '1:81111578667:web:7698c1ae0dcfd468e8126e',
    messagingSenderId: '81111578667',
    projectId: 'pinotes-flutter-project',
    authDomain: 'pinotes-flutter-project.firebaseapp.com',
    storageBucket: 'pinotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItITTDN-K5OCU3Btd6ynqenWGUFr-JcE',
    appId: '1:81111578667:android:83ed48dc9a31c400e8126e',
    messagingSenderId: '81111578667',
    projectId: 'pinotes-flutter-project',
    storageBucket: 'pinotes-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDucLYeCkVev6OeJGhAFGjqrsj0lUmjWTs',
    appId: '1:81111578667:ios:ceb42dde54c3fdf7e8126e',
    messagingSenderId: '81111578667',
    projectId: 'pinotes-flutter-project',
    storageBucket: 'pinotes-flutter-project.appspot.com',
    iosClientId: '81111578667-55lone21pvfqllk347votmfo19jilnhk.apps.googleusercontent.com',
    iosBundleId: 'pi.api.pinotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDucLYeCkVev6OeJGhAFGjqrsj0lUmjWTs',
    appId: '1:81111578667:ios:2ed2075cef650782e8126e',
    messagingSenderId: '81111578667',
    projectId: 'pinotes-flutter-project',
    storageBucket: 'pinotes-flutter-project.appspot.com',
    iosClientId: '81111578667-rren2kh1r8t2aq09nghkve1rhm6jehg9.apps.googleusercontent.com',
    iosBundleId: 'pi.api.pinotes.RunnerTests',
  );
}
